### ISSUE TITLE
jar does not run

### ISSUE THREAD

**Issue by robsoncardosoti** [keensoft/alfresco-deleted-content-store-cleaner#2]
Angel

I copied the jar to the $ ALFRESCO_HOME / modules / platform directory and changed the alfresco-global.properties, but the jar did not run and the recycle bin was not deleted. The Alfresco 5.2 server is in Gentoo Linux. Can you run the jar manually to check for possible errors?

**Comment by angelborroy-ks** [comment]
The recycle bin is deleted by [trash can cleaner module](https://docs.alfresco.com/community/concepts/trashcan-cleaner.html), which is provided by default from Alfresco 5.2.

These addon will remove `/opt/alfresco/alf_data/contentstore.deleted` files after 14 + 30 days.
